#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "game.h"
#include "images/garbage.h"
                    /* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"


                    /* TODO: */
// Add any additional states you need for your app.
typedef enum {
    START,
    PLAY,
    WIN,
    LOSE,
} GBAState;

typedef struct Swatter {
  int x;
  int y;
  int width;
  int height;
} Swatter;

void moveSwatter(Swatter* p, int s);
void drawPlayer(Swatter* p);
void undrawPlayer(Swatter* p, int s);

void undraw(Swatter* p, int s) {

	int x = p->x;
	int y = p->y;
    int w = p->width;
    int h = p->height;

    if(KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
        drawRectDMA(x + w, y, s, h, BLACK);   
    }
    
    if(KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
        drawRectDMA(x - s, y, s, h, BLACK);
    }

	if(KEY_DOWN(BUTTON_UP, BUTTONS)) {
		drawRectDMA(x, y + h, w, s, BLACK);
	}

	if(KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
		drawRectDMA(x, y - s, w, s, BLACK);
	}
}

void moveSwatter(Swatter* p, int s) {
    waitForVBlank();
    if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
        p->x = p->x - s;
    } else if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
        p->x = p->x + s; 
    } else if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
        p->y = p->y + s; 
    } else if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
        p->y = p->y - s;
    }
    drawPlayer(p);
    undraw(p, s);
}

void drawPlayer(Swatter* p) {
	waitForVBlank();
	// drawImageDMA(p->x, p->y, p->w, p->h, player);
    drawRectDMA(p->x, p->y, p->width, p->height, RED);
}

int main(void) {
                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    waitForVBlank();

    // drawImageDMA(10, 10, 25, 25, garbage);
    // drawFullScreenImageDMA(garbage);
    fillScreenDMA(RED);

    // Save current and previous state of button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state
    GBAState state = START;

    Swatter playerSwatter = {0, 0, 10, 10};
    Swatter *p = &playerSwatter;

    while (1) {
        currentButtons = BUTTONS; // Load the current state of the buttons


                    /* TODO: */
        // Manipulate the state machine below as needed //
        // NOTE: Call waitForVBlank() before you draw

        waitForVBlank();
        moveSwatter(p, 3);

        switch(state) {
            case START:

                // state = ?
                break;
            case PLAY:

                // state = ?
                break;
            case WIN:

                // state = ?
                break;
            case LOSE:
            
                // state = ?
                break;
        }



        previousButtons = currentButtons; // Store the current state of the buttons
    }

    UNUSED(previousButtons); // You can remove this once previousButtons is used

    return 0;
}
